### ISSUE TITLE
[Design] apply back-ground animation effect

### ISSUE THREAD

**Issue by Jieunwang0** [my-cinema/front-end#2]
# 📢 Issue
배경 애니메이션 이펙트

## 📃 Todo
백그라운드 이미지에 애니메이션 적용

### ✔️ Check
- [x] 웹 뷰포트 크기를 리사이징해도 배경에 이상이 느껴지지 않도록 구현한다
- [x] 랜덤한 값을 주어 위치를 지정한다
- [x] 반응형으로 적용하여 기기별 마우스 이벤트, 터치 이벤트가 적용되었을 때 이상이 없도록 한다
